[2025-09-03T16:39:03.453+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-03T16:39:03.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T16:39:01.631976+00:00 [queued]>
[2025-09-03T16:39:03.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T16:39:01.631976+00:00 [queued]>
[2025-09-03T16:39:03.474+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-03T16:39:03.479+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_for_interval> on 2025-09-03 16:39:01.631976+00:00
[2025-09-03T16:39:03.482+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cs_ingestion_monthly', 'fetch_for_interval', 'manual__2025-09-03T16:39:01.631976+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_cs.py', '--cfg-path', '/tmp/tmpkay1quc9']
[2025-09-03T16:39:03.483+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask fetch_for_interval
[2025-09-03T16:39:03.483+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-03T16:39:03.484+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2025-09-03T16:39:03.501+0000] {task_command.py:426} INFO - Running <TaskInstance: cs_ingestion_monthly.fetch_for_interval manual__2025-09-03T16:39:01.631976+00:00 [running]> on host cd1378bab084
[2025-09-03T16:39:03.531+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cs_ingestion_monthly' AIRFLOW_CTX_TASK_ID='fetch_for_interval' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T16:39:01.631976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T16:39:01.631976+00:00'
[2025-09-03T16:39:03.531+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-03T16:39:03.532+0000] {dag_cs.py:47} INFO - Starting ingestion task
[2025-09-03T16:39:03.532+0000] {dag_cs.py:72} INFO - Processing window: 2025-08-01 00:00:00 -> 2025-09-01 00:00:00
[2025-09-03T16:39:03.532+0000] {dag_cs.py:79} WARNING - Package function import failed (No module named 'ingestion'); trying package module
[2025-09-03T16:39:03.532+0000] {dag_cs.py:86} WARNING - Package module import failed (No module named 'ingestion'); trying top-level module
[2025-09-03T16:39:03.753+0000] {dag_cs.py:91} INFO - Imported top-level ingestion_cs module
[2025-09-03T16:39:03.754+0000] {ingestion_cs.py:45} INFO - Formatting datetime 2025-08-01 00:00:00 to arXiv format.
[2025-09-03T16:39:03.754+0000] {ingestion_cs.py:45} INFO - Formatting datetime 2025-08-31 23:59:00 to arXiv format.
[2025-09-03T16:39:04.000+0000] {ingestion_cs.py:156} INFO - [2025-08] got 100 (start=0)
[2025-09-03T16:39:07.449+0000] {ingestion_cs.py:156} INFO - [2025-08] got 200 (start=200)
[2025-09-03T16:39:10.785+0000] {ingestion_cs.py:156} INFO - [2025-08] got 200 (start=400)
[2025-09-03T16:39:14.254+0000] {ingestion_cs.py:156} INFO - [2025-08] got 200 (start=600)
[2025-09-03T16:39:17.601+0000] {ingestion_cs.py:156} INFO - [2025-08] got 200 (start=800)
[2025-09-03T16:39:20.861+0000] {ingestion_cs.py:156} INFO - [2025-08] got 200 (start=1000)
[2025-09-03T16:39:24.358+0000] {ingestion_cs.py:156} INFO - [2025-08] got 200 (start=1200)
[2025-09-03T16:39:27.525+0000] {ingestion_cs.py:120} INFO - [2025-08] Empty page at start=1400; retry 1 after short backoff.
[2025-09-03T16:39:30.734+0000] {ingestion_cs.py:120} INFO - [2025-08] Empty page at start=1400; retry 2 after short backoff.
[2025-09-03T16:39:34.843+0000] {ingestion_cs.py:123} INFO - [2025-08] No more entries at start=1400.
[2025-09-03T16:39:34.844+0000] {ingestion_cs.py:161} INFO - Result: 1300 entries fetched for window 2025-08-01 00:00:00 to 2025-08-31 23:59:00.
[2025-09-03T16:39:34.897+0000] {dag_cs.py:133} INFO - Saved CSV with 1300 rows to /opt/***/logs/data/arxiv_cs_20250801_20250901.csv
[2025-09-03T16:39:34.928+0000] {dag_cs.py:149} ERROR - Failed to write Parquet to GCS: File /opt/***/keys/google-credentials.json was not found.
[2025-09-03T16:39:34.929+0000] {dag_cs.py:155} ERROR - Task failed with error: File /opt/***/keys/google-credentials.json was not found.
[2025-09-03T16:39:34.929+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-03T16:39:34.929+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_cs.py", line 142, in run_ingestion_for_window
    df.to_parquet(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3118, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 482, in to_parquet
    impl.write(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 199, in write
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 123, in _get_path_or_handle
    fs, path_or_handle = fsspec.core.url_to_fs(
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/core.py", line 415, in url_to_fs
    fs = filesystem(protocol, **inkwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/registry.py", line 322, in filesystem
    return cls(**storage_options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/spec.py", line 81, in __call__
    obj = super().__call__(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gcsfs/core.py", line 337, in __init__
    self.credentials = GoogleCredentials(
                       ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/gcsfs/credentials.py", line 54, in __init__
    self.connect(method=token)
  File "/home/airflow/.local/lib/python3.12/site-packages/gcsfs/credentials.py", line 284, in connect
    self.__getattribute__("_connect_" + method)()
  File "/home/airflow/.local/lib/python3.12/site-packages/gcsfs/credentials.py", line 81, in _connect_google_default
    credentials, project = gauth.default(scopes=[self.scope])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
                              ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_default.py", line 650, in <lambda>
    lambda: _get_explicit_environ_credentials(quota_project_id=quota_project_id),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_default.py", line 270, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_default.py", line 114, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File /opt/***/keys/google-credentials.json was not found.
[2025-09-03T16:39:34.937+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=cs_ingestion_monthly, task_id=fetch_for_interval, run_id=manual__2025-09-03T16:39:01.631976+00:00, execution_date=20250903T163901, start_date=20250903T163903, end_date=20250903T163934
[2025-09-03T16:39:34.942+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task fetch_for_interval (File /opt/***/keys/google-credentials.json was not found.; 265)
[2025-09-03T16:39:34.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-03T16:39:34.964+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-03T16:39:34.964+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
